### ISSUE TITLE
setup.py error 

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [ydLiu-HIT/Psi-caller#3]
Hi,
I got an error while doing the **setup.py** file from **mantalib** and I don't know what could be the issue behind it.. 

"running install
running bdist_egg
running egg_info
writing mantaAss_module.egg-info/PKG-INFO
writing dependency_links to mantaAss_module.egg-info/dependency_links.txt
writing top-level names to mantaAss_module.egg-info/top_level.txt
reading manifest file 'mantaAss_module.egg-info/SOURCES.txt'
writing manifest file 'mantaAss_module.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'mantaAss_module' extension
gcc -pthread -DNDEBUG -O2 -fPIC -I/home/ionadmin/anaconda3/envs/bassyouni/include -c mantaAssembler.cpp -o build/temp.linux-x86_64-3.6/mantaAssembler.o -O3 -Wno-error=declaration-after-statement
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from mantaAssembler.hpp:18,
                 from mantaAssembler.cpp:25:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \"

That's part of the error I got if you can help, Thanks..

**Comment by ydLiu-HIT** [comment]
Hi, I think the lower version of c++ causes the problem. I have add '-std=c++17' compiler flag to use c++17. You can download the new release v1.0.1(https://github.com/ydLiu-HIT/Psi-caller/archive/refs/tags/v1.0.1.zip) and rerun the program. If wrong, you can check the version of c++ or gcc in your computer.

Best
Yadong

**Comment by Mahmoudbassuoni** [comment]
Thanks for the quick reply, it's now working fine I think!  I am closing the issue now.,,, 

Best Reagrds,
Mahmoud
